import Dexie from "dexie";
import { getNeteaseLyrics, getNeteasePlayInfo, getPlaylistTracks, getUserPlaylists, getUserRecordWithCounts, type NeteaseSearchResult } from "./music-service";
export type CompanionSyncProgress = { stage: "metadata" | "lyrics" | "done"; current: number; total: number; text: string };
export type CompanionLibraryTrack = { id: number; title: string; artist: string; album?: string; coverUrl?: string; playlistNames: string[]; liked: boolean; playCount: number; excerpt?: string; updatedAt: number; playable?: boolean; playableCheckedAt?: number; lyrics?: string };
type StoredLyrics = { songId: number; text: string; updatedAt: number };
export type RoleSongMemory = { key: string; characterId: string; trackId: string; understanding?: string; selectedCount: number; skippedCount: number; lastSelectedAt?: number };
type SyncState = { key: string; playlistId: number; songIds: number[]; syncedAt: number };
export type CompanionLibrary = { tracks: Record<string, CompanionLibraryTrack>; syncedAt: number };
export type CompanionLibraryStats = { trackCount: number; lyricCount: number; syncedAt?: number };
class MusicCompanionDb extends Dexie { tracks!: Dexie.Table<CompanionLibraryTrack, number>; lyrics!: Dexie.Table<StoredLyrics, number>; roleMemories!: Dexie.Table<RoleSongMemory, string>; syncState!: Dexie.Table<SyncState, string>; constructor() { super("AiPhoneMusicCompanionDB"); this.version(1).stores({ tracks: "id, liked, updatedAt", lyrics: "songId, updatedAt", roleMemories: "key, characterId, trackId, lastSelectedAt", syncState: "key, syncedAt" }); } }
const db = new MusicCompanionDb();
export async function getCompanionLibraryStats(): Promise<CompanionLibraryStats> { const [trackCount, lyricCount, state] = await Promise.all([db.tracks.count(), db.lyrics.count(), db.syncState.get("liked")]); return { trackCount, lyricCount, syncedAt: state?.syncedAt }; }
function cleanLyrics(raw = ""): string { return raw.split(/\r?\n/).map(line => line.replace(/^(?:\[[^\]]+\])+\s*/, "").trim()).filter(line => line.length >= 2 && !/^(作词|作曲|编曲|制作人)/.test(line)).join("\n"); }
export function representativeLyrics(raw = "", maxLines = 14): string { const lines = cleanLyrics(raw).split("\n").filter(Boolean); if (lines.length <= maxLines) return lines.join(" / "); const positions = [0.08, 0.2, 0.34, 0.48, 0.62, 0.76, 0.9]; const picked: string[] = []; for (const p of positions) { const start = Math.max(0, Math.min(lines.length - 2, Math.floor(lines.length * p))); picked.push(...lines.slice(start, start + 2)); } return [...new Set(picked)].slice(0, maxLines).join(" / "); }
async function mapLimit<T>(items: T[], limit: number, task: (item: T, index: number) => Promise<void>): Promise<void> { let cursor = 0; await Promise.all(Array.from({ length: Math.min(limit, items.length) }, async () => { while (cursor < items.length) { const index = cursor++; await task(items[index], index); } })); }
function toTrack(song: NeteaseSearchResult, playlistName: string, playCount: number, previous?: CompanionLibraryTrack): CompanionLibraryTrack { return { id: song.id, title: song.name, artist: song.artists || "未知歌手", album: song.album, coverUrl: song.coverUrl, playlistNames: [playlistName], liked: true, playCount, excerpt: previous?.excerpt, updatedAt: Date.now(), playable: previous?.playable, playableCheckedAt: previous?.playableCheckedAt }; }
export async function syncCompanionLibrary(onProgress?: (progress: CompanionSyncProgress) => void): Promise<CompanionLibrary> {
    onProgress?.({ stage: "metadata", current: 0, total: 1, text: "正在读取红心收藏" }); const [playlists, records] = await Promise.all([getUserPlaylists(), getUserRecordWithCounts(0)]); const liked = playlists.find(item => item.specialType === 5) || playlists.find(item => item.name.includes("喜欢的音乐")); if (!liked) throw new Error("没有找到“我喜欢的音乐”，请确认网易云已登录");
    const songs = await getPlaylistTracks(liked.id); const oldTracks = new Map((await db.tracks.toArray()).map(track => [track.id, track])); const counts = new Map(records.map(item => [item.song.id, item.playCount])); const tracks = songs.map(song => toTrack(song, liked.name, counts.get(song.id) || 0, oldTracks.get(song.id))); const currentIds = new Set(tracks.map(track => track.id));
    await db.transaction("rw", db.tracks, db.lyrics, db.syncState, async () => { await db.tracks.bulkPut(tracks); const removed = [...oldTracks.keys()].filter(id => !currentIds.has(id)); if (removed.length) { await db.tracks.bulkDelete(removed); await db.lyrics.bulkDelete(removed); } await db.syncState.put({ key: "liked", playlistId: liked.id, songIds: [...currentIds], syncedAt: Date.now() }); });
    const existingLyrics = new Set((await db.lyrics.bulkGet([...currentIds])).filter(Boolean).map(item => item!.songId)); const missing = tracks.filter(track => !existingLyrics.has(track.id)); let done = 0; onProgress?.({ stage: "lyrics", current: 0, total: missing.length, text: missing.length ? `正在补充收藏歌词 0/${missing.length}` : "收藏歌词已是最新" });
    await mapLimit(missing, 6, async track => { const text = cleanLyrics(await getNeteaseLyrics(track.id).catch(() => "")); if (text) { await db.lyrics.put({ songId: track.id, text, updatedAt: Date.now() }); await db.tracks.update(track.id, { excerpt: representativeLyrics(text, 14) }); } done += 1; onProgress?.({ stage: "lyrics", current: done, total: missing.length, text: `正在补充收藏歌词 ${done}/${missing.length}` }); });
    const finalTracks = await db.tracks.toArray(); const state = await db.syncState.get("liked"); onProgress?.({ stage: "done", current: finalTracks.length, total: finalTracks.length, text: `红心歌曲已缓存 ${finalTracks.length} 首` }); return { tracks: Object.fromEntries(finalTracks.map(track => [String(track.id), track])), syncedAt: state?.syncedAt || Date.now() };
}
export async function ensureLyrics(tracks: CompanionLibraryTrack[]): Promise<CompanionLibraryTrack[]> { const rows = await db.lyrics.bulkGet(tracks.map(track => track.id)); return tracks.map((track, index) => ({ ...track, lyrics: rows[index]?.text || "" })); }
export async function filterPlayableTracks(tracks: CompanionLibraryTrack[]): Promise<CompanionLibraryTrack[]> { const now = Date.now(); const staleAfter = 12 * 60 * 60 * 1000; const result: CompanionLibraryTrack[] = []; await mapLimit(tracks, 2, async track => { if (track.playable === true && track.playableCheckedAt && now - track.playableCheckedAt < staleAfter) { result.push(track); return; } const info = await getNeteasePlayInfo(track.id).catch(() => ({ url: null, reason: "网络异常" })); const hardBlocked = !info.url && /无版权|已下架|所在地区|需购买|付费专辑/.test(info.reason || ""); const updated = { ...track, playable: info.url ? true : hardBlocked ? false : undefined, playableCheckedAt: now }; await db.tracks.put(updated); if (!hardBlocked) result.push(updated); }); return tracks.map(track => result.find(item => item.id === track.id)).filter((track): track is CompanionLibraryTrack => Boolean(track)); }
export async function loadRoleSongMemories(characterId: string): Promise<RoleSongMemory[]> { return db.roleMemories.where("characterId").equals(characterId).toArray(); }
export async function saveRoleSongMemories(characterId: string, updates: Array<Partial<RoleSongMemory> & { trackId: string }>): Promise<void> { for (const update of updates) { const key = `${characterId}:${update.trackId}`; const current = await db.roleMemories.get(key); await db.roleMemories.put({ ...current, ...update, key, characterId, trackId: update.trackId, selectedCount: (current?.selectedCount || 0) + (update.selectedCount || 0), skippedCount: (current?.skippedCount || 0) + (update.skippedCount || 0) }); } }
export async function chooseLibraryCandidates(library: CompanionLibrary, characterId: string, count = 80): Promise<CompanionLibraryTrack[]> { const memories = new Map((await loadRoleSongMemories(characterId)).map(item => [item.trackId, item])); const scored = Object.values(library.tracks).map(track => { const memory = memories.get(String(track.id)); const novelty = memory?.lastSelectedAt ? Math.min(30, (Date.now() - memory.lastSelectedAt) / 86_400_000) : 40; return { track, score: 45 + Math.min(35, Math.log2(track.playCount + 1) * 7) + novelty - (memory?.skippedCount || 0) * 8 + Math.random() * 18 }; }).sort((a, b) => b.score - a.score); const chosen: CompanionLibraryTrack[] = []; const artists = new Map<string, number>(); for (const item of scored) { if (chosen.length >= count) break; const used = artists.get(item.track.artist) || 0; if (used >= 3) continue; chosen.push(item.track); artists.set(item.track.artist, used + 1); } return chosen; }
