import { kvGet, kvSet, registerKvMigration } from "./kv-db";
import { getNeteaseLyrics, getNeteasePlayInfo, getPlaylistTracks, getUserPlaylists, getUserRecordWithCounts, type NeteaseSearchResult } from "./music-service";
const LIBRARY_KEY = "ai_phone_music_companion_library_v1"; const ROLE_MEMORY_KEY = "ai_phone_music_companion_role_memory_v1"; registerKvMigration(LIBRARY_KEY); registerKvMigration(ROLE_MEMORY_KEY);
export type CompanionLibraryTrack = { id: number; title: string; artist: string; album?: string; coverUrl?: string; playlistNames: string[]; liked: boolean; playCount: number; lyrics?: string; lyricsUpdatedAt?: number; playable?: boolean; playableCheckedAt?: number };
export type CompanionLibrary = { tracks: Record<string, CompanionLibraryTrack>; syncedAt: number };
export type RoleSongMemory = { characterId: string; trackId: string; understanding?: string; selectedCount: number; skippedCount: number; lastSelectedAt?: number };
const emptyLibrary = (): CompanionLibrary => ({ tracks: {}, syncedAt: 0 });
export function loadCompanionLibrary(): CompanionLibrary { try { const raw = kvGet(LIBRARY_KEY); return raw ? { ...emptyLibrary(), ...JSON.parse(raw) } : emptyLibrary(); } catch { return emptyLibrary(); } }
function saveCompanionLibrary(value: CompanionLibrary): void { kvSet(LIBRARY_KEY, JSON.stringify(value)); }
export function loadRoleSongMemories(characterId: string): RoleSongMemory[] { try { const all = JSON.parse(kvGet(ROLE_MEMORY_KEY) || "[]") as RoleSongMemory[]; return all.filter(item => item.characterId === characterId); } catch { return []; } }
export function saveRoleSongMemories(characterId: string, updates: Array<Partial<RoleSongMemory> & { trackId: string }>): void { let all: RoleSongMemory[] = []; try { all = JSON.parse(kvGet(ROLE_MEMORY_KEY) || "[]") as RoleSongMemory[]; } catch { /* empty */ } const map = new Map(all.map(item => [`${item.characterId}:${item.trackId}`, item])); for (const update of updates) { const key = `${characterId}:${update.trackId}`; const current = map.get(key); map.set(key, { ...current, ...update, characterId, trackId: update.trackId, selectedCount: (current?.selectedCount || 0) + (update.selectedCount || 0), skippedCount: (current?.skippedCount || 0) + (update.skippedCount || 0) }); } kvSet(ROLE_MEMORY_KEY, JSON.stringify([...map.values()])); }
function mergeTrack(target: CompanionLibraryTrack | undefined, song: NeteaseSearchResult, playlistName?: string, liked = false, playCount = 0): CompanionLibraryTrack { const names = new Set(target?.playlistNames || []); if (playlistName) names.add(playlistName); return { id: song.id, title: song.name, artist: song.artists || "未知歌手", album: song.album, coverUrl: song.coverUrl, playlistNames: [...names], liked: Boolean(target?.liked || liked), playCount: Math.max(target?.playCount || 0, playCount), ...(target?.lyrics ? { lyrics: target.lyrics, lyricsUpdatedAt: target.lyricsUpdatedAt } : {}) }; }
export async function syncCompanionLibrary(): Promise<CompanionLibrary> { const library = loadCompanionLibrary(); const [playlists, records] = await Promise.all([getUserPlaylists(), getUserRecordWithCounts(0)]); for (const record of records) { const key = String(record.song.id); library.tracks[key] = mergeTrack(library.tracks[key], record.song, undefined, false, record.playCount); } const batches = await Promise.all(playlists.map(async playlist => ({ playlist, songs: await getPlaylistTracks(playlist.id) }))); for (const { playlist, songs } of batches) { const liked = playlist.specialType === 5 || playlist.name.includes("喜欢的音乐"); for (const song of songs) { const key = String(song.id); library.tracks[key] = mergeTrack(library.tracks[key], song, playlist.name, liked); } } library.syncedAt = Date.now(); saveCompanionLibrary(library); return library; }
async function mapLimit<T>(items: T[], limit: number, task: (item: T) => Promise<void>): Promise<void> { let cursor = 0; await Promise.all(Array.from({ length: Math.min(limit, items.length) }, async () => { while (cursor < items.length) await task(items[cursor++]); })); }
export async function ensureLyrics(tracks: CompanionLibraryTrack[]): Promise<CompanionLibraryTrack[]> { const library = loadCompanionLibrary(); const missing = tracks.filter(track => !library.tracks[String(track.id)]?.lyrics); await mapLimit(missing, 6, async track => { const lyrics = await getNeteaseLyrics(track.id).catch(() => ""); if (lyrics) library.tracks[String(track.id)] = { ...library.tracks[String(track.id)], lyrics, lyricsUpdatedAt: Date.now() }; }); if (missing.length) saveCompanionLibrary(library); return tracks.map(track => library.tracks[String(track.id)] || track); }
export async function filterPlayableTracks(tracks: CompanionLibraryTrack[]): Promise<CompanionLibraryTrack[]> { const library = loadCompanionLibrary(); const now = Date.now(); const staleAfter = 12 * 60 * 60 * 1000; await mapLimit(tracks, 6, async track => { const stored = library.tracks[String(track.id)] || track; if (stored.playable === true && stored.playableCheckedAt && now - stored.playableCheckedAt < staleAfter) return; const info = await getNeteasePlayInfo(track.id).catch(() => ({ url: null })); library.tracks[String(track.id)] = { ...stored, playable: Boolean(info.url), playableCheckedAt: now }; }); saveCompanionLibrary(library); return tracks.map(track => library.tracks[String(track.id)] || track).filter(track => track.playable); }
export function chooseLibraryCandidates(library: CompanionLibrary, characterId: string, count = 80): CompanionLibraryTrack[] { const memories = new Map(loadRoleSongMemories(characterId).map(item => [item.trackId, item])); const scored = Object.values(library.tracks).map(track => { const memory = memories.get(String(track.id)); const novelty = memory?.lastSelectedAt ? Math.min(30, (Date.now() - memory.lastSelectedAt) / 86_400_000) : 40; return { track, score: (track.liked ? 45 : 0) + Math.min(35, Math.log2(track.playCount + 1) * 7) + novelty - (memory?.skippedCount || 0) * 8 + Math.random() * 18 }; }).sort((a, b) => b.score - a.score); const chosen: CompanionLibraryTrack[] = []; const artistCounts = new Map<string, number>(); for (const item of scored) { if (chosen.length >= count) break; const used = artistCounts.get(item.track.artist) || 0; if (used >= 3) continue; chosen.push(item.track); artistCounts.set(item.track.artist, used + 1); } return chosen; }
export function representativeLyrics(raw = "", maxLines = 14): string { const lines = raw.split(/\r?\n/).map(line => line.replace(/^(?:\[[^\]]+\])+\s*/, "").trim()).filter(line => line.length >= 2 && !/^(作词|作曲|编曲|制作人|纯音乐)/.test(line)); if (lines.length <= maxLines) return lines.join(" / "); const positions = [0.08, 0.2, 0.34, 0.48, 0.62, 0.76, 0.9]; const picked: string[] = []; for (const p of positions) { const start = Math.max(0, Math.min(lines.length - 2, Math.floor(lines.length * p))); picked.push(...lines.slice(start, start + 2)); } return [...new Set(picked)].slice(0, maxLines).join(" / "); }
